events {}

http {
    upstream grafana {
        server grafana:3000;
    }

    upstream backend {
        server fastapi_app:8000;
    }

    server {
        listen 80;

        location = /auth-grafana {
            internal;
            proxy_pass http://backend/auth/grafana;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;

            # пробрасываем cookie с JWT
            proxy_set_header Cookie $http_cookie;
        }

        location /grafana/ {
            auth_request /auth-grafana;

            error_page 401 = @login;

            proxy_set_header X-WEBAUTH-USER $upstream_http_x_webauth_user;
            proxy_set_header X-WEBAUTH-ROLE $upstream_http_x_webauth_role;

            proxy_pass http://grafana/;
        }

        location @login {
            return 302 http://your-frontend/login;
        }
    }
}
