apiVersion: 1

datasources:
  - name: PrometheusTest
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    orgId: 1

  - name: LokiTest
    type: loki
    access: proxy
    url: http://loki:3100
    orgId: 1
